import type { Card } from './types';

export const INITIAL_CARDS: Card[] = [
  {
    name: 'Sleep Pod',
    tags: ['Technology', 'Sleep', 'Pod'],
    description: 'A sleep pod is a device that allows you to sleep in a pod. It is a small, portable device that you can take with you wherever you go. It is a great way to get a good night\'s sleep on the go.',
    colors: ['#3C5BD7', '#123AAF'],
    details: 'Compact, sound-dampened enclosure with temperature control and optional white noise. Designed for naps or full sleep cycles in offices, airports, or home.',
    effects: 'Improves sleep quality on the go, reduces jet lag, enhances daytime alertness after power naps.',
  },
  {
    name: 'Mindful Moments',
    tags: ['Mindfulness', 'Calm', 'Focus'],
    description: 'Practice staying present in the moment with guided mindfulness techniques to help reduce anxiety and stress.',
    colors: ['#1b5e20', '#004d40'],
    details: 'Short guided sessions (5–15 min) using body scans, breath awareness, and sensory grounding. Audio prompts help redirect attention from rumination.',
    effects: 'Lowers cortisol, reduces anxious thoughts, improves focus and emotional regulation.',
  },
  {
    name: 'Gratitude Journal',
    tags: ['Gratitude', 'Wellbeing', 'Journaling'],
    description: 'Keep track of things you are grateful for each day to boost positivity and overall emotional wellness.',
    colors: ['#c17f0a', '#5c3d0a'],
    details: 'Daily prompts to log 3–5 things you’re grateful for. Optional themes: people, experiences, small wins, or challenges that taught you something.',
    effects: 'Boosts mood, shifts perspective toward positivity, strengthens resilience and life satisfaction.',
  },
  {
    name: 'Deep Breathing',
    tags: ['Relaxation', 'Breathing', 'Anxiety'],
    description: 'Relax with simple deep breathing exercises designed to soothe your nervous system and ease tension.',
    colors: ['#006064', '#004d40'],
    details: 'Structured patterns like 4-7-8 or box breathing. Inhale, hold, exhale at set counts to activate the parasympathetic nervous system.',
    effects: 'Slows heart rate, reduces tension, calms anxiety and promotes relaxation within minutes.',
  },
  {
    name: 'Sleep Routine',
    tags: ['Sleep', 'Rest', 'Self-care'],
    description: 'Create a healthy nightly routine to improve your sleep quality and support your mental resilience.',
    colors: ['#1a237e', '#0d2137'],
    details: 'Step-by-step wind-down: dim lights, avoid screens, light stretching, reading or meditation. Consistent timing trains your body’s sleep-wake cycle.',
    effects: 'Faster sleep onset, deeper sleep stages, better next-day energy and mental clarity.',
  },
  {
    name: 'Mood Tracker',
    tags: ['Mood', 'Awareness', 'Habits'],
    description: 'Track your mood every day to increase self-awareness and discover patterns in emotional wellbeing.',
    colors: ['#c2185b', '#6a1b9a'],
    details: 'Log mood 1–2x daily with optional notes. View trends over days, weeks, or months. Identify triggers and patterns linked to sleep, stress, or habits.',
    effects: 'Increases self-awareness, reveals emotional patterns, supports better decision-making about self-care.',
  },
  {
    name: 'Night Wind Down',
    tags: ['Sleep', 'Relaxation', 'Evening'],
    description: 'Wind down before bed with calming activities to prepare your mind and body for restful sleep.',
    colors: ['#1a237e', '#0d47a1'],
    details: 'Evening ritual combining gentle movement, breathing, and sensory cues (e.g., lavender, soft music). 20–30 min before target bedtime.',
    effects: 'Eases transition into sleep, reduces racing thoughts, improves sleep quality and morning freshness.',
  },
  {
    name: 'Stress Release',
    tags: ['Stress', 'Relief', 'Tension'],
    description: 'Release built-up tension with targeted exercises and techniques to melt away daily stress.',
    colors: ['#4a148c', '#6a1b9a'],
    details: 'Progressive muscle relaxation, neck/shoulder stretches, and breath-focused release. Targets common tension areas from desk work and stress.',
    effects: 'Releases physical tension, lowers stress hormones, restores a sense of ease and bodily comfort.',
  },
  {
    name: 'Focus Flow',
    tags: ['Focus', 'Productivity', 'Concentration'],
    description: 'Enter a state of deep focus with structured sessions designed to minimize distractions.',
    colors: ['#004d40', '#00695c'],
    details: 'Timed work blocks (e.g., 25–50 min) with clear goals, minimal context-switching, and short breaks. Optional ambient sound or silence.',
    effects: 'Deepens concentration, increases output quality, reduces mental fatigue from multitasking.',
  },
  {
    name: 'Calm Anchor',
    tags: ['Anxiety', 'Grounding', 'Calm'],
    description: 'Anchor yourself in the present when anxiety rises with grounding and breathing techniques.',
    colors: ['#1b5e20', '#2e7d32'],
    details: '5-4-3-2-1 sensory grounding: name 5 things you see, 4 you hear, 3 you touch, 2 you smell, 1 you taste. Paired with slow breathing.',
    effects: 'Interrupts anxiety spirals, brings you back to the present, restores a sense of safety and control.',
  },
  {
    name: 'Restful Nights',
    tags: ['Sleep', 'Insomnia', 'Recovery'],
    description: 'Overcome sleeplessness with evidence-based strategies for falling and staying asleep.',
    colors: ['#0d1b2a', '#1b263b'],
    details: 'Sleep restriction, stimulus control, and cognitive reframing. Limit time in bed to actual sleep, get up if awake 20+ min, avoid clock-watching.',
    effects: 'Strengthens sleep drive, reduces sleep anxiety, improves sleep efficiency and consistency.',
  },
  {
    name: 'Emotional Reset',
    tags: ['Emotions', 'Reset', 'Balance'],
    description: 'Reset your emotional state with guided practices to restore balance and perspective.',
    colors: ['#880e4f', '#ad1457'],
    details: 'Guided emotional check-in, naming feelings without judgment, and perspective-shifting prompts. Optional journaling or brief movement.',
    effects: 'Regulates intense emotions, creates distance from reactivity, restores emotional equilibrium.',
  },
  {
    name: 'Quiet Mind',
    tags: ['Meditation', 'Silence', 'Clarity'],
    description: 'Find stillness and mental clarity through guided meditation and quiet reflection.',
    colors: ['#4527a0', '#5e35b1'],
    details: 'Guided sitting meditation (10–20 min) with breath or body focus. Gentle instructions for noticing thoughts without engaging. Optional silence periods.',
    effects: 'Reduces mental chatter, sharpens clarity, cultivates a calmer baseline state of mind.',
  },
  {
    name: 'Energy Restore',
    tags: ['Energy', 'Rest', 'Recovery'],
    description: 'Restore depleted energy with short restorative practices that fit into your busy day.',
    colors: ['#1a472a', '#2d5a27'],
    details: '5–10 min micro-practices: legs-up-the-wall, brief breathing reset, or a short walk. Designed for lunch breaks or between meetings.',
    effects: 'Recharges mental and physical energy, reduces afternoon slump, supports sustained performance.',
  },
  {
    name: 'Inner Peace',
    tags: ['Peace', 'Serenity', 'Wellbeing'],
    description: 'Cultivate inner peace through practices that nurture a sense of calm and contentment.',
    colors: ['#0d2137', '#1e3a5f'],
    details: 'Loving-kindness meditation, self-compassion phrases, and gentle reflection on what brings you peace. Combines visualization and affirmation.',
    effects: 'Builds lasting calm, reduces self-criticism, fosters a stable sense of wellbeing.',
  },
  {
    name: 'Sleep Sanctuary',
    tags: ['Sleep', 'Environment', 'Comfort'],
    description: 'Transform your bedroom into a sleep sanctuary with tips for optimal rest conditions.',
    colors: ['#311b92', '#4a148c'],
    details: 'Optimize temperature (cool), light (dark), noise (quiet or white noise), and bedding. Reserve the room for sleep and intimacy only.',
    effects: 'Improves sleep environment, strengthens sleep association, supports deeper and more restorative rest.',
  },
];
